### ISSUE TITLE
Room information missing, weird subject name

### ISSUE THREAD

**Issue by andreas-aeschlimann** [gymmuenchenstein/gym-lessons-angular-application#42]
What is going on here with the subject and room name for teacher Ae?

<img width="270" alt="image" src="https://github.com/gymmuenchenstein/gym-lessons-angular-application/assets/2174826/4d16088f-974b-4798-a622-d5de4e7abd02">

**Comment by ThisRedstony** [comment]
Those seem to be actual entries in the data.

(line 307-309)
```
Ae,2024,1,22,1,FMS As.,,,0,,31,800,45,
Ae,2024,1,22,2,FMS As.,,,0,,31,855,45,
Ae,2024,1,22,3,FMS As.,,,0,,31,1000,45,
Ae,2024,1,22,4,FMS As.,,,0,,31,1055,45,
```
