### ISSUE TITLE
Adjust detail info on timetable lesson for teacher and room

### ISSUE THREAD

**Issue by andreas-aeschlimann** [gymmuenchenstein/gym-lessons-angular-application#45]
If a teacher or room is selected, it does not make sense to show the information again in the timetable lesson slot.

Instead, we should change the information displayed:

Class selected:
IN
Aa | 112

Teacher selected:
IN
M1a | 112

Room selected:
IN
Aa | M1a

If there are multiple classes, display "vd." instead ("multiple").

**Comment by ThisRedstony** [comment]
done,
