### ISSUE TITLE
Check possible error in data or parser: multiple teachers in one room

### ISSUE THREAD

**Issue by andreas-aeschlimann** [gymmuenchenstein/gym-lessons-angular-application#48]
Tuesday afternoon a Math lesson shows "vd" as teachers. When you click the lesson, two teachers are shown in the detail view. The second teacher already has another lesson on the same time.

Is this a CSV error or a parsing error?

<img width="1644" alt="Screenshot 2024-03-07 at 01 52 04" src="https://github.com/gymmuenchenstein/gym-lessons-angular-application/assets/2174826/75e2df6e-a268-49a2-bd0a-aa024268b35f">

**Comment by ThisRedstony** [comment]
fixed, pls approve pull request
