### ISSUE TITLE
Implement app routing

### ISSUE THREAD

**Issue by andreas-aeschlimann** [gymmuenchenstein/gym-lessons-angular-application#56]
We should implement app routes for different timetables. This will allow people to send and save links.

**Comment by ThisRedstony** [comment]
Proposition:
.../timetable_name?active_filters

_Active filters_ being things one can also enter into the search field in the sidebar menu. f.e. _?abbr=Aa&lesson=fIN_

(We may also need to look over the entire filter system again to allow for multiple selected filters at once)

**Comment by ThisRedstony** [comment]
/timetable/date
/date
